### ISSUE TITLE
[Q] Is there anyway to hide id in text?

### ISSUE THREAD

**Issue by enisn** [EasyAbp/Abp.TagHelperPlus#3]
Hi,
I'm using EasySelector and it displays id of each object after their names. 

Can I hide Id in dropdown texts? Is there any way to do it?

**Comment by enisn** [comment]
I've found a css trick:

```css
.selection-subtext
{
    display:none;
}
```
